### ISSUE TITLE
pystamps doesn't work from the command line on OS X - IndexError

### ISSUE THREAD

**Issue by godber** [planetarypy/pystamps#1]
Pystamps has an `IndexError` on the command line no matter what arguments I provide.

```
pystamps
pystamps tests/mission_data/
pystamps tests/mission_data/*img
pystamps tests/mission_data/0047MH0000110010100214C00_DRCL.IMG
```

The error is as follows

```
 pystamps tests/mission_data/1p190678905erp64kcp2600l8c1.img
Traceback (most recent call last):
  File "/Users/godber/.virtualenvs/pystamsp/bin/pystamps", line 9, in <module>
    load_entry_point('pystamps==0.1.0', 'console_scripts', 'pystamps')()
  File "/Users/godber/Workspace/planetarypy/pystamps/pystamps/pystamps.py", line 525, in cli
    pystamps(args.file)
  File "/Users/godber/Workspace/planetarypy/pystamps/pystamps/pystamps.py", line 499, in pystamps
    display = MainWindow(image_set.images)
  File "/Users/godber/Workspace/planetarypy/pystamps/pystamps/pystamps.py", line 270, in __init__
    self.main_window_set()
  File "/Users/godber/Workspace/planetarypy/pystamps/pystamps/pystamps.py", line 277, in main_window_set
    title_height = self.images[0].title.height()
IndexError: list index out of range
```

Using python `Python 2.7.10`.

pip environment is

```
astropy==1.0.3
flake8==2.4.1
ginga==2.4.20150725031607
mccabe==0.3.1
numpy==1.9.2
pdsview==0.3.0
pep8==1.5.7
planetary-test-data==0.3.3
planetaryimage==0.2.0
pluggy==0.3.0
pvl==0.1.1
py==1.4.30
pyflakes==0.8.1
PySide==1.2.2
-e git+git@github.com:planetarypy/pystamps.git@9fbf88ecd843eec676a5335e5660fb8474ec3e5c#egg=pystamps-master
pytest==2.7.2
pytest-qt==1.5.0
pytz==2015.4
six==1.9.0
tox==2.1.1
virtualenv==13.1.0
wheel==0.23.0
```

**Comment by percurnicus** [comment]
Did you run `pyside_postinstall.py -install`? Im also updating pystamps so if there are no pds images the window comes up blank.
